# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: lumensigner.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AddressInformation(betterproto.Message):
    """
    AddressInformation is used to share address information with other
    applications.
    """

    # BIP-32 path, must be m/44'/148'/index'
    derivation_path: str = betterproto.string_field(1)
    # address in SEP-23 format, ex:
    # GBQTENG6SON3BA5556OXSDOC553GZUF3H2QZ4WIX4BFWWY6OGCFWJEOK
    address: str = betterproto.string_field(2)
