import pytest
import unicodedata
from seedsigner.models.seed import InvalidSeedException, Seed, ElectrumSeed

from seedsigner.models.settings import SettingsConstants

from conftest import TEST_PASSPHRASES

# TODO: Change TAB indents to SPACE

def test_seed():
	# Test seed with passphrase
	seed_1 = Seed(mnemonic="obscure bone gas open exotic abuse virus bunker shuffle nasty ship dash".split(), passphrase=TEST_PASSPHRASES[0])
	
	# Seed bytes are generated using trezor/python-mnemonic library and setting language as "English" and mnemonic phrase as the mnemonic above
	# with the passphrases specified in TEST_PASSPHRASES
	assert seed_1.seed_bytes == b'\x13\xc8\xdfn\x17\xf4\xb3\x06n\x12\xfd\x1bE\x0c\x8d\x819\xe2\xf1\x9ar\xc1j\xde\x14<\xe8\x98\x8e\xd8=\xb8\x94j\x9a\x0c\xaf\xf4\x04\xa6s\xc8\xb4\xd3\xf1\xd4\x85\xde\x84u\xac\x88\\p\xeb\xcf\xbd\xc4A\xb5\xa1\xc3\xb1\xfa'
	
	assert seed_1.mnemonic_str == "obscure bone gas open exotic abuse virus bunker shuffle nasty ship dash"
	
	assert seed_1.passphrase == unicodedata.normalize("NFKD", TEST_PASSPHRASES[0])
	
	# Test seed with a special character passphrase
	seed_2 = Seed(mnemonic="obscure bone gas open exotic abuse virus bunker shuffle nasty ship dash".split(), passphrase=TEST_PASSPHRASES[1])
	
	assert seed_2.seed_bytes == b'\xea\xe4\xd6\xb5\x17\x91L\x12h\x9a\x96\x06\x08\x13\xf6\xe3\x80O\x9d\xa8\xeaU\xc8\xef\xbeSx\xe6\xb91\xc4\xd2_\xda\xae\x9a\xda\xc18q\x1b\x15u\xe6f\x8cw\xc1\x10\x8b\x94gV\x85\x10\xf4Rp[\x06\x8c\x89o\x07'
	
	assert seed_2.mnemonic_str == "obscure bone gas open exotic abuse virus bunker shuffle nasty ship dash"
	
	assert seed_2.passphrase == unicodedata.normalize("NFKD", TEST_PASSPHRASES[1])
	
	# TODO: Not yet supported in new implementation
	# seed.set_wordlist_language_code("es")
	
	# assert seed.mnemonic_str == "natural ayuda futuro nivel espejo abuelo vago bien repetir moreno relevo conga"
	
	# seed.set_wordlist_language_code(SettingsConstants.WORDLIST_LANGUAGE__ENGLISH)
	
	# seed.mnemonic_str = "height demise useless trap grow lion found off key clown transfer enroll"
	
	# assert seed.mnemonic_str == "height demise useless trap grow lion found off key clown transfer enroll"
	
	# # TODO: Not yet supported in new implementation
	# seed.set_wordlist_language_code("es")
	
	# assert seed.mnemonic_str == "hebilla cría truco tigre gris llenar folio negocio laico casa tieso eludir"
	
	# seed.set_passphrase("test")
	
	# assert seed.seed_bytes == b'\xdd\r\xcb\x0b V\xb4@\xee+\x01`\xabem\xc1B\xfd\x8fba0\xab;[\xab\xc9\xf9\xba[F\x0c5,\x7fd8\xebI\x90"\xb8\x86C\x821\x01\xdb\xbe\xf3\xbc\x1cBH"%\x18\xc2{\x04\x08a]\xa5'
	
	# assert seed.passphrase == "test"

	
def test_electrum_seed():
	"""
	ElectrumSeed should correctly parse a modern Electrum mnemonic.
	"""
	seed = ElectrumSeed(mnemonic="regular reject rare profit once math fringe chase until ketchup century escape".split())

	intended_seed = b'\xcan|\xf8\x8a\x8d\xf78=Pq\xc4_\xe6\x02\x91\xfcs\xb2[\xed*\xdc\xc7%\xb6[_-(~D\xe5\x1e\x85%N\x9c\x03\x9dh\xafX}\x16\xb1\x99,\xbe\xc4\x11\xfaW\x0f\xb0\x89yD\xf4\x0f\xd5?\x8eA'

	assert seed.seed_bytes == intended_seed


def test_electrum_mnemonic_format():
	"""
	ElectrumSeed should reject mnemonics that are not 12 words long.
	"""
	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic=["regular"] * 11)

	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic=["regular"] * 13)

	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic=["regular"] * 24)


def test_electrum_seed_rejects_most_bip39_mnemonics():
	"""
	ElectrumSeed should throw an exception for most BIP-39 mnemonics.

	There are 1/16 odds that a seed will be valid for both formats.
	"""
	# Most BIP-39 seeds should fail; test seeds generated by bitcoiner.guide
	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic="pioneer divide volcano art victory family grow novel mandate bicycle senior adjust".split())

	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic="gentle combine cool hamster ghost harvest gossip lend dismiss slam any toast".split())

	with pytest.raises(InvalidSeedException):
		ElectrumSeed(mnemonic="enough board blossom stamp fire buffalo digital solution sadness random number stone".split())

	# This one is valid for both formats
	mnemonic = "only gain spot output unknown craft simple cram absorb suggest ridge famous".split()
	Seed(mnemonic)
	ElectrumSeed(mnemonic)
